/*  eddy.c - The simplest kernel module.

注意会在该路径下添加这个设备节点
/sys/bus/platform/drivers/eddy

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/mm.h>  		//remap_pfn_range
#include <linux/cdev.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("kevin.wang.");
MODULE_DESCRIPTION
    ("eddy - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "eddy"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct eddy_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t eddy_irq(int irq, void *lp)
{
	printk("eddy interrupt\n");
	return IRQ_HANDLED;
}

static int eddy_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct eddy_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct eddy_local *) kmalloc(sizeof(struct eddy_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate eddy device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "eddy: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "eddy at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int)(long)(lp->base_addr));
			//(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &eddy_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"eddy at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)(lp->mem_start),
		(unsigned int )(long)(lp->base_addr),
		//(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int eddy_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct eddy_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

static struct of_device_id eddy_of_match[] = {
	{ .compatible = "vendor eddy", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, eddy_of_match);

static int device_mmap(struct file *filp, struct vm_area_struct *vma) {
	unsigned long start = (unsigned long)vma->vm_start; 
	unsigned long size = (unsigned long)(vma->vm_end - vma->vm_start); 

	//得到物理地址 
	//vma->vm_flags |= VM_RESERVED;
	vma->vm_flags |= VM_DONTEXPAND | VM_DONTDUMP;
	vma->vm_flags |= VM_IO;
	vma->vm_page_prot=pgprot_noncached(vma->vm_page_prot);
	//将用户空间的一个vma虚拟内存区映射到以page开始的一段连续物理页面上 
	if(remap_pfn_range(vma,start,0x43C00000>>PAGE_SHIFT,size,vma->vm_page_prot))	//第三个参数是页帧号，由物理地址右移PAGE_SHIFT得到 
	{
		printk("Error mapping fail!\n");
		return -EAGAIN;
	}
	else
		printk("Mapping OK!\n");


	return 0;
}

static int device_open(struct inode * mindoe, struct file *mfile) {
        printk(KERN_ALERT "eddy module be open!\n");
	return 0;
}

static int device_release(struct inode *minode, struct file *mfile) {
        printk(KERN_ALERT "eddy module be release!\n");
	return 0;
}

static struct platform_driver eddy_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= eddy_of_match,
	},
	.probe		= eddy_probe,
	.remove		= eddy_remove,
};

struct file_operations eddy_fops = {
       .open  	 = device_open,
       .release  = device_release,
       .mmap	 = device_mmap,
};

static int __init eddy_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&eddy_driver);
}


static void __exit eddy_exit(void)
{
	platform_driver_unregister(&eddy_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(eddy_init);
module_exit(eddy_exit);
